apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: custom-policy
  namespace: default-managed-tenant
spec:
  description: Custom policy that excludes High CVEs to allow CVE-2026-4111
  name: Custom
  publicKey: k8s://openshift-pipelines/public-key
  sources:
  - name: Custom
    policy:
    - oci::quay.io/conforma/release-policy:konflux@sha256:6eb386faaf76de0d7dbc9f9e770a7f5639ebcee88e4ed4f004f8053189b21eae
    data:
    - oci::quay.io/konflux-ci/tekton-catalog/data-acceptable-bundles:latest
    - github.com/redhat-appstudio/tsf-conforma-data//data?ref=33b9228b4f2846d827128e776b4a956788d7df8a
    - k8s://default-managed-tenant/ec-cve-exceptions
    config:
      exclude:
      - hermetic_task
      - source_image
      - rpm_repos
      - cve.cve_blockers:CVE-2026-4111
      include:
      - '@redhat'
